package com.lesslag.web;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.lesslag.LessLag;
import com.lesslag.setup.backup.ConfigBackup;
import com.lesslag.setup.model.RollbackBundle;

import org.bukkit.command.CommandSender;

import java.io.File;
import java.io.FileReader;
import java.util.Map;

/**
 * Reads {@code plugins/LessLag/lesslag-config.json} (generated by the web configurator)
 * and applies the {@code lesslag} block to LessLag's {@code config.yml}.
 *
 * <p>The {@code server_config_expectations} block is NOT applied — those must be set
 * manually in the respective server config files. Use {@code /lg verify} to check them.
 *
 * <p>A backup is created before applying. Run {@code /lg restore} to roll back.
 */
public class ApplyConfigCommand {

    private static final Gson GSON = new Gson();
    private static final String CONFIG_JSON_NAME = "lesslag-config.json";

    private final LessLag plugin;

    public ApplyConfigCommand(LessLag plugin) {
        this.plugin = plugin;
    }

    public void execute(CommandSender sender) {
        File configJson = new File(plugin.getDataFolder(), CONFIG_JSON_NAME);
        if (!configJson.exists()) {
            LessLag.sendMessage(sender, plugin.getPrefix()
                + "<red>No <white>lesslag-config.json<red> found in <white>plugins/LessLag/<red>.");
            LessLag.sendMessage(sender, plugin.getPrefix()
                + "<gray>Generate one at <aqua>https://lesslag-web.vercel.app<gray> with <aqua>/lg web link<gray>.");
            return;
        }

        JsonObject root;
        try (FileReader reader = new FileReader(configJson)) {
            root = GSON.fromJson(reader, JsonObject.class);
        } catch (Exception e) {
            LessLag.sendMessage(sender, plugin.getPrefix()
                + "<red>Failed to read lesslag-config.json: <white>" + e.getMessage());
            return;
        }

        if (!root.has("lesslag") || !root.get("lesslag").isJsonObject()) {
            LessLag.sendMessage(sender, plugin.getPrefix()
                + "<red>lesslag-config.json is missing the <white>\"lesslag\"<red> block.");
            return;
        }

        // ── 1. Backup ────────────────────────────────────────────────────────
        ConfigBackup backup = new ConfigBackup(plugin.getDataFolder());
        RollbackBundle bundle = backup.createSnapshot("apply-cmd");
        if (bundle != null) {
            LessLag.sendMessage(sender, plugin.getPrefix()
                + "<gray>Config backup created. Token: <white>" + bundle.getRollbackToken()
                + " <dark_gray>(use <white>/lg restore<dark_gray> to roll back)");
        }

        // ── 2. Apply lesslag block ────────────────────────────────────────────
        JsonObject lesslagBlock = root.getAsJsonObject("lesslag");
        int applied = 0;
        for (Map.Entry<String, JsonElement> entry : lesslagBlock.entrySet()) {
            String key = entry.getKey();
            Object value = jsonElementToJava(entry.getValue());
            plugin.getConfig().set(key, value);
            applied++;
        }

        plugin.saveConfig();
        plugin.reloadPlugin();

        // ── 3. Report ─────────────────────────────────────────────────────────
        LessLag.sendMessage(sender, "");
        LessLag.sendMessage(sender, "<green><bold>  ✓ Applied " + applied + " setting(s) to config.yml.");
        LessLag.sendMessage(sender, "");
        LessLag.sendMessage(sender, "  <gray>Run <aqua>/lg verify<gray> to check server config expectations.");
        if (root.has("server_config_expectations")) {
            JsonObject expectations = root.getAsJsonObject("server_config_expectations");
            int totalFiles = expectations.size();
            LessLag.sendMessage(sender, "  <yellow>" + totalFiles + " server config file(s) have manual changes — see <aqua>/lg verify<yellow>.");
        }
        LessLag.sendMessage(sender, "");
    }

    private static Object jsonElementToJava(JsonElement el) {
        if (el.isJsonNull()) return null;
        if (el.isJsonPrimitive()) {
            var prim = el.getAsJsonPrimitive();
            if (prim.isBoolean()) return prim.getAsBoolean();
            if (prim.isNumber()) {
                double d = prim.getAsDouble();
                if (d == Math.floor(d) && !Double.isInfinite(d) && Math.abs(d) < Integer.MAX_VALUE)
                    return (int) d;
                return d;
            }
            return prim.getAsString();
        }
        // Arrays/objects fall through as strings for config.yml compatibility
        return el.toString();
    }
}
